import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'outline-variant': '#c6c7bd',
        'on-primary-fixed': '#141e0d',
        'surface-container-highest': '#e3e3de',
        'on-tertiary-fixed': '#251a05',
        error: '#ba1a1a',
        'on-surface': '#1b1c19',
        'surface-tint': '#56624c',
        'on-tertiary-container': '#ab9678',
        'on-secondary': '#ffffff',
        'surface-dim': '#dbdad5',
        'tertiary-container': '#3d2f18',
        'tertiary-fixed-dim': '#dac3a2',
        'inverse-surface': '#30312e',
        'secondary-fixed': '#ede1ca',
        outline: '#76786f',
        'on-secondary-container': '#6a624f',
        'primary-fixed-dim': '#becbb0',
        'on-tertiary-fixed-variant': '#54442b',
        'on-secondary-fixed': '#201b0d',
        'surface-container': '#efeee9',
        'on-primary-container': '#919e85',
        'inverse-on-surface': '#f2f1ec',
        'on-error-container': '#93000a',
        tertiary: '#261a05',
        'on-error': '#ffffff',
        'primary-container': '#2a3522',
        'primary-fixed': '#dae7cb',
        'error-container': '#ffdad6',
        'inverse-primary': '#becbb0',
        'on-tertiary': '#ffffff',
        primary: '#16200e',
        surface: '#faf9f4',
        'secondary-container': '#eadfc7',
        'on-primary': '#ffffff',
        'surface-container-high': '#e9e8e3',
        background: '#faf9f4',
        'on-background': '#1b1c19',
        'secondary-fixed-dim': '#d0c5af',
        'on-secondary-fixed-variant': '#4d4635',
        'surface-container-low': '#f5f4ef',
        'on-surface-variant': '#454840',
        'tertiary-fixed': '#f7dfbd',
        'surface-bright': '#faf9f4',
        secondary: '#665e4b',
        'surface-variant': '#e3e3de',
        'on-primary-fixed-variant': '#3f4a36',
        'surface-container-lowest': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Work Sans', 'sans-serif'],
        body: ['Newsreader', 'serif'],
        label: ['Work Sans', 'sans-serif'],
      },
    },
  },
  plugins: [forms],
};
